spring:
  application:
    name: dairy
  datasource:
    url: jdbc:postgresql://localhost:5432/dairy_db
    username: postgres
    password: Aashu0429
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # creates/updates tables automatically
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: local
  app:
    security:
      jwt:
        access-token-expiration: 86400000 # 1 day in milliseconds
        refresh-token-expiration: 604800000 # 7 days in milliseconds
