spring:
  application:
    name: dairy

  datasource:
    url: jdbc:postgresql://localhost:5432/dairy_db
    username: postgres
    password: Aashu0429
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # creates/updates tables automatically
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
